/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hp.design.material.materialone.beer.pojo;

public class Available {
	private Integer id;

 	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	private String name;

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	private String description;

 	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

}