/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hp.design.material.materialone.beer.pojo;

public class Beer {
	public int currentpage;
    private int numberofpages;
    private int totalresults;
    private BeerElement[] data;
    private String status;

    public void setCurrentpage(int currentpage) {
		this.currentpage = currentpage;
	}

	public int getCurrentpage() {
		return currentpage;
	}

 	public void setNumberofpages(int numberofpages) {
		this.numberofpages = numberofpages;
	}

	public int getNumberofpages() {
		return numberofpages;
	}


 	public void setData(BeerElement[] data) {
		this.data = data;
	}


	public BeerElement[] getData() {
		return data;
	}


 	public void setTotalresults(int totalresults) {
		this.totalresults = totalresults;
	}

	public int getTotalresults() {
		return totalresults;
	}


 	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

}