/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hp.design.material.materialone.beer.pojo;

public class BeerElement {
    private Labels labels;
    
	private String statusdisplay;

 	public void setStatusdisplay(String statusdisplay) {
		this.statusdisplay = statusdisplay;
	}

	public String getStatusdisplay() {
		return statusdisplay;
	}

	private java.lang.Integer availableid;

 	public void setAvailableid(java.lang.Integer availableid) {
		this.availableid = availableid;
	}

	public java.lang.Integer getAvailableid() {
		return availableid;
	}

	private String ibu;

 	public void setIbu(String ibu) {
		this.ibu = ibu;
	}

	public String getIbu() {
		return ibu;
	}

	private String updatedate;

 	public void setUpdatedate(String updatedate) {
		this.updatedate = updatedate;
	}

	public String getUpdatedate() {
		return updatedate;
	}

	private String isorganic;

 	public void setIsorganic(String isorganic) {
		this.isorganic = isorganic;
	}

	public String getIsorganic() {
		return isorganic;
	}

	private java.lang.Integer styleid;

 	public void setStyleid(java.lang.Integer styleid) {
		this.styleid = styleid;
	}

	public java.lang.Integer getStyleid() {
		return styleid;
	}

	private String status;

 	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	private String createdate;

 	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	public String getCreatedate() {
		return createdate;
	}

	private String namedisplay;

 	public void setNamedisplay(String namedisplay) {
		this.namedisplay = namedisplay;
	}

	public String getNamedisplay() {
		return namedisplay;
	}

	private String id;

 	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	private Available available;

 	public void setAvailable(Available available) {
		this.available = available;
	}

	public Available getAvailable() {
		return available;
	}

	private Style style;

 	public void setStyle(Style style) {
		this.style = style;
	}

	public Style getStyle() {
		return style;
	}

	private String abv;

 	public void setAbv(String abv) {
		this.abv = abv;
	}

	public String getAbv() {
		return abv;
	}

	private String name;

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	private String description;

 	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

    public Labels getLabels() {
        return labels;
    }

    public void setLabels(Labels labels) {
        this.labels = labels;
    }
}