/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hp.design.material.materialone.beer.pojo;

public class Category {
	private java.lang.String createdate;

 	public void setCreatedate(java.lang.String createdate) {
		this.createdate = createdate;
	}

	public java.lang.String getCreatedate() {
		return createdate;
	}

	private java.lang.Integer id;

 	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}