/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hp.design.material.materialone.beer.pojo;

public class Style {
	private java.lang.String ogmin;

 	public void setOgmin(java.lang.String ogmin) {
		this.ogmin = ogmin;
	}

	public java.lang.String getOgmin() {
		return ogmin;
	}

	private Category category;

 	public void setCategory(Category category) {
		this.category = category;
	}

	public Category getCategory() {
		return category;
	}

	private java.lang.String ibumin;

 	public void setIbumin(java.lang.String ibumin) {
		this.ibumin = ibumin;
	}

	public java.lang.String getIbumin() {
		return ibumin;
	}

	private java.lang.String fgmax;

 	public void setFgmax(java.lang.String fgmax) {
		this.fgmax = fgmax;
	}

	public java.lang.String getFgmax() {
		return fgmax;
	}

	private java.lang.String fgmin;

 	public void setFgmin(java.lang.String fgmin) {
		this.fgmin = fgmin;
	}

	public java.lang.String getFgmin() {
		return fgmin;
	}

	private java.lang.String srmmin;

 	public void setSrmmin(java.lang.String srmmin) {
		this.srmmin = srmmin;
	}

	public java.lang.String getSrmmin() {
		return srmmin;
	}

	private java.lang.String updatedate;

 	public void setUpdatedate(java.lang.String updatedate) {
		this.updatedate = updatedate;
	}

	public java.lang.String getUpdatedate() {
		return updatedate;
	}

	private java.lang.String srmmax;

 	public void setSrmmax(java.lang.String srmmax) {
		this.srmmax = srmmax;
	}

	public java.lang.String getSrmmax() {
		return srmmax;
	}

	private java.lang.Integer categoryid;

 	public void setCategoryid(java.lang.Integer categoryid) {
		this.categoryid = categoryid;
	}

	public java.lang.Integer getCategoryid() {
		return categoryid;
	}

	private java.lang.String ibumax;

 	public void setIbumax(java.lang.String ibumax) {
		this.ibumax = ibumax;
	}

	public java.lang.String getIbumax() {
		return ibumax;
	}

	private java.lang.String abvmin;

 	public void setAbvmin(java.lang.String abvmin) {
		this.abvmin = abvmin;
	}

	public java.lang.String getAbvmin() {
		return abvmin;
	}

	private java.lang.String abvmax;

 	public void setAbvmax(java.lang.String abvmax) {
		this.abvmax = abvmax;
	}

	public java.lang.String getAbvmax() {
		return abvmax;
	}

	private java.lang.String shortname;

 	public void setShortname(java.lang.String shortname) {
		this.shortname = shortname;
	}

	public java.lang.String getShortname() {
		return shortname;
	}

	private java.lang.String createdate;

 	public void setCreatedate(java.lang.String createdate) {
		this.createdate = createdate;
	}

	public java.lang.String getCreatedate() {
		return createdate;
	}

	private java.lang.Integer id;

 	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	private java.lang.String description;

 	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getDescription() {
		return description;
	}

}